let projectJSON = {
  "Bakery": "bakery",
  "befresh": "befresh",
  "Bernie’s brewing Co": "bernie_brewing",
  "Checkmate": "checkmate",
  "Choice-book": "choice_book",
  "Club 500": "club500",
  "dales_branding": "dales_brand",
  "Dmitroskiye ovoshi": "dmitrovskie_ovoshi",
  "EASY CASE": "easecase",
  "Eat For Fit": "earforfit",
  "EMVY": "emvy",
  "frumba": "frumba",
  "geon": "geon",
  "InGame": "ingame",
  "J Curl": "jcurl",
  "Jocc": "jocc",
  "korolev": "korolev",
  "koya": "koya",
  "kustendorf": "kustendorf",
  "life": "life_site",
  "life-branding": "life_brand",
  "majestic": "majestic",
  "Mation": "mation",
  "milk": "milk",
  "Moon Dream Recordings": "moon_dream",
  "Nochnoi-kontakt": "night_contact",
  "Pencil": "pencil",
  "pims": "pims",
  "Qiwi": "qiwi",
  "RFO": "rfo",
  "Silvashi": "silvashi",
  "Super": "super",
  "team": "team",
  "True Food": "truefood",
  "tut-prosto": "tutprosto",
  "vkusnoteevo": "vkusnoteevo",
  "Water": "water",
  "Willgrade": "willgrade",
};

let expressJSON = {
  "Anyway": "anyway",
  "Bonpoke": "bonpoke",
  "Doskishop": "doskishop",
  "Drug stepei": "drug_stepei",
  "Gymholiday": "gymholiday",
  "INTACTO": "intacto",
  "Koroche": "koroche",
  "Kvartel": "kvartel",
  "Lovilavash": "lovilavash",
  "Moidom": "moidom",
  "Moon Dream Recordings": "moon_dream",
  "RFO": "rfo_express",
  "Truefood": "truefood",
};